baseURL = "https://www.flavorsdiscovered.com"
languageCode = "en-us"
paginate = "10"
summaryLength = "5"
theme = "parsa-hugo"
title = "Flavors Discovered"
[[menu.main]]
URL = "categories/travel/"
name = "Travel"
weight = "2"
[[menu.main]]
URL = "categories/recipes/"
name = "Recipes"
weight = "2"
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
address = ""
author = "Nikita"
author_image = "/images/img_2514.JPG"
bio = "Digital Marketer by day, foodie 24/7"
contact_form_action = ""
copyright = "Copyright &copy; 2020 - Nikita K."
description = "This is meta description"
email = "nikitaflavors@gmail.com"
google_analitycs_id = "UA-126623668-1"
home = ""
layout = "1"
logo = "images/fd-logo-small.png"
mobile = ""
preloader = true
search = true
[params.instafeed]
access_token = "EAATNWLjQkwkBABBEuuopdAvtiTjdXWGTNU8aj0O4ax0MTzyTezd8oJJZCTcZAZAl2ieJxnBC6W2KMyWqRZBtsfqm6cSHPH4sWmGc4CCzILVHZAMBOe4GIhQ0MrhnUZCGlyPYkF1JcefuHc0dPjolic3f5OHQezhzIVzbx3rT7dYnZBmCGPocIB6BTXExLguNMPqHu3ocTceaPH1ADxCO2RF "
enable = true
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.social]]
URL = "https://www.instagram.com/flavorsdiscovered/"
icon = "ti-instagram"
